### ISSUE TITLE
A few Embedly errors when scraping our top_sites.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tippy-top-sites-deprecated#23]
~~Not sure if this belongs here or in the [**mozilla/embedly-proxy**](https://github.com/mozilla/embedly-proxy/) repo yet.~~ Looks like Embedly issue.

I build a pretty crude little scraper to scrape the contents of our top sites and noticed that I'm currently getting 4 results back with defined `error_message` strings:

```
http://www.groupon.com/ =>  HTTP 403: Forbidden
http://www.lowes.com/   =>  HTTP 403: Forbidden
http://realtor.com      =>  HTTP 503: Service Unavailable
http://pinterest.com    =>  HTTP 550: Unknown
```

I can also reproduce by hitting the Embed.ly proxy directly: https://embedly-proxy.dev.mozaws.net/extract?urls=http://www.groupon.com/&urls=http://www.lowes.com/&urls=http://realtor.com&urls=http://pinterest.com

Here's my :poop: code:

``` js
// curl -XPOST https://embedly-proxy.dev.mozaws.net/v2/extract -H "Content-Type:application/json" -d '{"urls":["http://bing.com"]}'

const fetch = require("node-fetch");
const chunk = require("lodash.chunk");

const data = require("./top_sites.json");

const EMBEDLY_PROXY_URL = "https://embedly-proxy.dev.mozaws.net/v2/extract";
const MAX_URLS_PER_REQUEST = 25;

fetchTopSites(data)
  .catch((err) => console.error);

function fetchTopSites(sites) {
  // "Chunk" the array of sites into smaller arrays of 25 to play nice w/ proxy.
  const urls = chunk(sites, MAX_URLS_PER_REQUEST).map(fetchBatch);

  return Promise.all(urls).then((data) => {
    var sites = [];
    data.forEach((res) => {
      for (url in res.urls) {
        var site = res.urls[url];
        sites.push(site);
        // Log any Embedly errors.
        if (site.type === "error") {
          console.info("%s\t=>\t%s", site.original_url, site.error_message);
        }
      }
    });
    return sites;
  })
}

function fetchBatch(sites) {
  return fetch(EMBEDLY_PROXY_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      urls: sites.map((site) => site.url)
    })
  }).then((res) => res.json());
}
```

In fact, here's the results directly from the embed.ly API:

| SITE | EMBED.LY URL | ERROR_CODE | ERROR_MESSAGE |
| --- | --- | --- | --- |
| Groupon | http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fwww.groupon.com%2F | 404 | HTTP 403: Forbidden |
| Lowes | http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fwww.lowes.com%2F | 404 | HTTP 403: Forbidden |
| Realtor | http://embed.ly/docs/explore/extract?url=http%3A%2F%2Frealtor.com | 404 | HTTP 503: Service Unavailable |
| Pinterest | http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fpinterest.com | 404 | HTTP 550: Unknown |

Looks like https://www.groupon.com/ ([Embedly](http://embed.ly/docs/explore/extract?url=https%3A%2F%2Fwww.groupon.com%2F)), and http://www.realtor.com ([Embedly](http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fwww.realtor.com%2F)) work, but I haven't been able to find the magic HTTPS+www combination for Lowes or Groupon though, so I'm guessing it must be an Embed.ly thing since I can definitely see all these sites if I browse to them directly.

**Comment by pdehaan** [comment]
Filed upstream to Embed.ly:
- Lowes: http://support.embed.ly/hc/en-us/requests/9722
- Pinterest: http://support.embed.ly/hc/en-us/requests/9723 (although I suspect is related to http://blog.embed.ly/post/119462317541/pinterest).

---

**UPDATE:** Responses from Embed.ly support:

> _Re: Lowes.com;_ 
> This is likely an automated blocking mechanism deployed by Lowes, some products sites do this to prevent price scraping.
> The error_message is from the upstream server.
> 
> ---
> 
> _Re: Pinterest.com;_
> We unfortunately cannot support Pinterest by their request: http://blog.embed.ly/post/119462317541/pinterest

**Comment by pdehaan** [comment]
If we want to be a bit obnoxious, we could test this in the unit tests (but means we'd almost always certainly fail the CI tests (unless we skillfully exclude the 2-4 specific domains above):

``` js
const fetch = require("node-fetch");

...

it("should be scrapeable by embedly", (done) => {
  fetchSite(site.url)
    .then((data) => {
      var res = data.urls[site.url];
      assert.isUndefined(res.error_message);
      // or `assert.notEqual(res.type, "error", res.error_message);`
      done();
    }).catch(done);
});

...

function fetchSite(url) {
  return fetch(EMBEDLY_PROXY_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      urls: [url]
    })
  }).then((res) => res.json());
}
```

#### Output:

```
  656 passing (22s)
  4 failing

  1) top_sites #38 Groupon should be scrapeable by embedly:
     AssertionError: expected 'HTTP 403: Forbidden' to equal undefined
      at Function.assert.isUndefined (node_modules/chai/lib/chai/interface/assert.js:478:32)
      at test/index.test.js:35:14

  2) top_sites #51 Lowes should be scrapeable by embedly:
     AssertionError: expected 'HTTP 403: Forbidden' to equal undefined
      at Function.assert.isUndefined (node_modules/chai/lib/chai/interface/assert.js:478:32)
      at test/index.test.js:35:14

  3) top_sites #64 Pinterest should be scrapeable by embedly:
     AssertionError: expected 'HTTP 550: Unknown' to equal undefined
      at Function.assert.isUndefined (node_modules/chai/lib/chai/interface/assert.js:478:32)
      at test/index.test.js:35:14

  4) top_sites #65 Realtor should be scrapeable by embedly:
     AssertionError: expected 'HTTP 503: Service Unavailable' to equal undefined
      at Function.assert.isUndefined (node_modules/chai/lib/chai/interface/assert.js:478:32)
      at test/index.test.js:35:14
```

**Comment by pdehaan** [comment]
Ignore me, I'm just having fun for some sick reason.

``` js
// TODO: SHAME!
const SKIP_EMBEDLY_CHECK = [
  "http://pinterest.com",
  "http://realtor.com",
  "http://www.groupon.com/",
  "http://www.lowes.com/"
];

...

      if (SKIP_EMBEDLY_CHECK.indexOf(site.url) !== -1) {
        it.skip("should be scrapeable by Embedly", () => {});
      } else {
        it("should be scrapeable by Embedly", (done) => {
          fetchSite(site.url)
            .then((data) => {
              var res = data.urls[site.url];
              assert.notEqual(res.type, "error", res.error_message);
              done();
            }).catch(done);
        });
      }
```

#### Output:

```
    #38 Groupon
      ✓ should be an object
      ✓ should have a non-empty title
      ✓ should have a valid url
      - should be scrapeable by Embedly
      ✓ should have an image_url pointing to a .png or .svg image prefixed with images/
      ✓ should have background color as a hex color
...
  656 passing (22s)
  4 pending
```
