### ISSUE TITLE
Add larger images for a few sites

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tippy-top-sites-deprecated#65]
### Steps to reproduce:
1. Run `npm test` in this repo.

### Actual results:

Six sites don't seem to have the higher-res assets:

1. dailymail
1. dailybeast
1. images.google
1. jcpenney
1. verizonwireless
1. wikia

```
  1563 passing (481ms)
  6 failing

  1) images/ should have an image with the correct width and height for dailymail:
     AssertionError: width: expected 64 to equal 128
      at Context.it (test/image-sizes.test.js:46:14)

  2) images/ should have an image with the correct width and height for dailybeast:
     AssertionError: width: expected 64 to equal 128
      at Context.it (test/image-sizes.test.js:46:14)

  3) images/ should have an image with the correct width and height for images.google:
     AssertionError: width: expected 64 to equal 128
      at Context.it (test/image-sizes.test.js:46:14)

  4) images/ should have an image with the correct width and height for jcpenney:
     AssertionError: width: expected 64 to equal 128
      at Context.it (test/image-sizes.test.js:46:14)

  5) images/ should have an image with the correct width and height for verizonwireless:
     AssertionError: width: expected 106 to equal 128
      at Context.it (test/image-sizes.test.js:46:14)

  6) images/ should have an image with the correct width and height for wikia:
     AssertionError: width: expected 64 to equal 128
      at Context.it (test/image-sizes.test.js:46:14)
```

**Comment by pdehaan** [comment]
`npm test` works locally vs master. Me thinks we already did this.
